name: Release APK

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Set up NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
        link-to-sdk: true
        
    - name: Set up Rust
      uses: hecrj/setup-rust-action@v2
      with:
        rust-version: 'stable'
        targets: 'armv7-linux-androideabi,aarch64-linux-android,i686-linux-android,x86_64-linux-android'

    - name: Build with Gradle
      run: ./gradlew --no-daemon assembleRelease
      
    - name: Run release
      run: |
        ./release.sh ${{ github.ref_name }}
        mkdir -p release/signed

    - name: Sign APK
      uses: Tlaster/android-sign@v1
      with:
        releaseDirectory: release
        output: release/signed
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        alias: ${{ secrets.ALIAS }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"

    - name: Attest APK
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: "release/signed/*"

    - name: Upload release files
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "release/signed/*"
